# Generated by Django 5.1.3 on 2024-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_line_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
