# Generated by Django 5.1.3 on 2024-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_profile_address_line_one_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_profile_photo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
