# Generated by Django 5.1.3 on 2024-12-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_deal_of_the_day_section_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
