# Generated by Django 5.1.3 on 2024-12-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userphone',
            old_name='phone_number',
            new_name='user_Phone',
        ),
    ]
