# Generated by Django 5.1.3 on 2024-12-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_phone_number_userphone_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
