# Generated by Django 5.1.3 on 2024-12-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
